"""Employee Password Added

Revision ID: 154acb23e660
Revises: 5c9a53df3ab9
Create Date: 2025-09-07 18:24:30.367994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154acb23e660'
down_revision = '5c9a53df3ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
