"""Initial Migrate

Revision ID: 5c9a53df3ab9
Revises: 
Create Date: 2025-09-07 15:34:28.475765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9a53df3ab9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('publisher', sa.String(length=50), nullable=False),
    sa.Column('publiYear', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('availNumber', sa.Integer(), nullable=False),
    sa.Column('totalNumber', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('registration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('registration')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('LoanBook', sa.Integer(), nullable=True),
    sa.Column('LoanStudent', sa.Integer(), nullable=True),
    sa.Column('returnDate', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['LoanBook'], ['book.id'], ),
    sa.ForeignKeyConstraint(['LoanStudent'], ['student.registration'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    op.drop_table('student')
    op.drop_table('employee')
    op.drop_table('book')
    # ### end Alembic commands ###
