"""Initial Migrate

Revision ID: 92d2fd29f3d9
Revises: 
Create Date: 2025-09-10 19:04:53.677975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d2fd29f3d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('publiYear', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('availNumber', sa.Integer(), nullable=False),
    sa.Column('totalNumber', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('registration')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loanBook', sa.Integer(), nullable=True),
    sa.Column('loanStudent', sa.Integer(), nullable=True),
    sa.Column('returnDate', sa.DateTime(), nullable=True),
    sa.Column('loanDate', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['loanBook'], ['book.id'], name='fk_loan_book'),
    sa.ForeignKeyConstraint(['loanStudent'], ['student.registration'], name='fk_loan_student'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    op.drop_table('student')
    op.drop_table('employee')
    op.drop_table('book')
    # ### end Alembic commands ###
