"""empty message

Revision ID: b7b7a76cfc87
Revises: 92d2fd29f3d9
Create Date: 2025-09-10 20:17:39.058268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b7a76cfc87'
down_revision = '92d2fd29f3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returnLimit', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('returnLimit')

    # ### end Alembic commands ###
